name: go-ethereum workflow

on:
  push:
    branches:
      - master
    tags:
      - '**'
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.20.5
    - name: Lint
      run: go run build/ci.go lint
    - name: Build
      run: go run build/ci.go install -dlgo

  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
      
    needs: lint
    steps:
    steps:
      
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.20.5
    - name: Cache testdata
      id: cache-testdata
      uses: actions/cache@v3
      with:
        path: |
          tests/testdata
        key: ${{ runner.os }}-testdata

    - name: Update git submodules
      if: steps.cache-testdata.outputs.cache-hit != 'true'
      run:
        git submodule update --init --depth 1 --recursive
    - name: Test
      run: go run build/ci.go test -dlgo
    
